### ISSUE TITLE
scattered::vector roadmap

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/scattered#1]
#### Functionality:
- [ ] enable move constructor only if exception safe
- [ ] enable constructors that take allocators?
- [ ] enable initializer lists?
- [ ] document member functions
- [ ] make sure doxygen documentation is nice
- [ ] fortify: assert preconditions in member functions
- [ ] cach template instantiations errors as soon as possible: e.g. static_assert
      that keys exist
- [ ] corner cases: static_assert empty structs?
- [ ] enable emplace_back?
- [ ] reasonable tests coverage
- [ ] user-defined comparison functor for floating point operations
- [ ] insert should take `InputIt` instead of `const_iterator`
#### Performance
- [ ] optimize relational operators
- [ ] improve insert (use the underlying container insert)
#### Testing:
- [ ] improve test struct: make template, use inheritance, add function pointers
  and arrays
- [ ] test more algorithms, rvalue references, exception safety, bit fields
- [ ] test using a std::vector instead of boost::container::vector
- [ ] test iterators and references extensively: reverse_iterator, const_iterator, 
     const_reference, const_pointer.
